# Generated by Django 6.0 on 2025-12-04 10:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_id_type', models.CharField(max_length=32)),
                ('party_identifier', models.CharField(max_length=128)),
                ('account_id', models.CharField(max_length=64, unique=True)),
                ('balance', models.BigIntegerField(default=0)),
                ('reserved', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BulkTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bulk_id', models.CharField(max_length=128, unique=True)),
                ('total_amount', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='XOF', max_length=8)),
                ('state', models.CharField(default='PENDING', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payer_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulk_payer', to='bulk.account')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_id', models.CharField(max_length=128, unique=True)),
                ('payee_party_id_type', models.CharField(max_length=32)),
                ('payee_party_identifier', models.CharField(max_length=128)),
                ('amount', models.BigIntegerField()),
                ('currency', models.CharField(default='XOF', max_length=8)),
                ('status', models.CharField(default='PENDING', max_length=32)),
                ('ilp_packet', models.TextField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, max_length=256, null=True)),
                ('fulfilment', models.CharField(blank=True, max_length=256, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('bulk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individuals', to='bulk.bulktransfer')),
                ('payee_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bulk.account')),
            ],
        ),
    ]
