# Generated by Django 5.2.9 on 2025-12-04 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '__first__'),
        ('bulk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organisation propriétaire du compte', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounts.organization'),
        ),
    ]
